const getCurrentProvince = () => {
  var province = { 'province_name': '上海市', 'province_no': '1' }
  return province
}

const getHistoryProvince = () => {
  var provinces = [{ 'province_name': '上海市', 'province_no': '1' }]
  return provinces
}

const getHotProvince = () => {
  var provinces = [{ 'province_name': '上海市', 'province_no': '1' },
  { 'province_name': '江苏省', 'province_no': '2' },
  { 'province_name': '浙江省', 'province_no': '3' },
  { 'province_name': '安徽省', 'province_no': '4' },
  { 'province_name': '山东省', 'province_no': '5' },
  { 'province_name': '河北省', 'province_no': '6' },
  { 'province_name': '天津市', 'province_no': '7' },
  { 'province_name': '北京市', 'province_no': '8' },
  { 'province_name': '河南省', 'province_no': '9' },
  { 'province_name': '辽宁省', 'province_no': '12' },
  { 'province_name': '湖北省', 'province_no': '14' }]
  return provinces
}

const getAllProvince = () => {
  var provinces = [{ 'province_name': '上海市', 'province_no': '1' },
  { 'province_name': '江苏省', 'province_no': '2' },
  { 'province_name': '浙江省', 'province_no': '3' },
  { 'province_name': '安徽省', 'province_no': '4' },
  { 'province_name': '山东省', 'province_no': '5' },
  { 'province_name': '河北省', 'province_no': '6' },
  { 'province_name': '天津市', 'province_no': '7' },
  { 'province_name': '北京市', 'province_no': '8' },
  { 'province_name': '河南省', 'province_no': '9' },
  { 'province_name': '吉林省', 'province_no': '10' },
  { 'province_name': '黑龙江省', 'province_no': '11' },
  { 'province_name': '辽宁省', 'province_no': '12' },
  { 'province_name': '内蒙古自治区', 'province_no': '13' },
  { 'province_name': '湖北省', 'province_no': '14' },
  { 'province_name': '湖南省', 'province_no': '15' },
  { 'province_name': '江西省', 'province_no': '16' },
  { 'province_name': '甘肃省', 'province_no': '17' },
  { 'province_name': '陕西省', 'province_no': '18' },
  { 'province_name': '四川省', 'province_no': '19' },
  { 'province_name': '重庆市', 'province_no': '20' },
  { 'province_name': '广东省', 'province_no': '21' },
  { 'province_name': '海南省', 'province_no': '22' },
  { 'province_name': '广西壮族自治区', 'province_no': '23' },
  { 'province_name': '福建省', 'province_no': '24' },
  { 'province_name': '云南省', 'province_no': '25' },
  { 'province_name': '贵州省', 'province_no': '26' },
  { 'province_name': '山西省', 'province_no': '35' },
  { 'province_name': '青海省', 'province_no': '37' },
  { 'province_name': '宁夏省', 'province_no': '39' }]
  return provinces
}


const getDefaultStore = (latitude, longitude) =>{
  var latitude = latitude
  var longitude = longitude
  var store = {
    province_no:1,
    province_name: "上海市",
    city_no:1,
    city_name: "上海市",
    store_no: 1063,
    store_name:"三林店"
  }
  return store
}

const getStoreLines = (storeNo) => {
  var lines = []
  if (storeNo == 1001){
    lines = [{
      'shuttle_lines': 6,
      'shuttle_memos': ['运营时间：周一、三、五、日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '闸北店1号线老北站中兴线',
      'shuttle_no': '1001_1',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '止园路芷江中路路口', 'station_no': 2 },
      { 'station_name': '芷园路近邮电小区', 'station_no': 3 },
      { 'station_name': '中兴路662号', 'station_no': 4 },
      { 'station_name': '宝昌路276号', 'station_no': 5 },
      { 'station_name': '宝山路499弄', 'station_no': 6 },
      { 'station_name': '北宝兴路246号嘉利明珠城东门对面', 'station_no': 7 },
      { 'station_name': '北宝兴路交66路区间车站', 'station_no': 8 },
      { 'station_name': '平型关路1083弄慧芝湖花园', 'station_no': 9 },
      { 'station_name': '平型关路1083弄慧芝湖花园', 'station_no': 10 },
      { 'station_name': '平型关路1501弄粤秀小区', 'station_no': 11 },
      { 'station_name': '永和东路明园森林都市', 'station_no': 12 },
      { 'station_name': '大润发到达时间', 'station_no': 13 },
      { 'station_name': '大润发出发时间', 'station_no': 14 }]
    },
    {
      'shuttle_lines': 9,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店2号线凉城新市线',
      'shuttle_no': '1001_2',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '丰镇路35号', 'station_no': 2 },
      { 'station_name': '新市北路1390弄文新小区', 'station_no': 3 },
      { 'station_name': '新市南路918弄新申小区', 'station_no': 4 },
      { 'station_name': '新市南路560弄新一小区', 'station_no': 5 },
      { 'station_name': '新市南路488弄546弄', 'station_no': 6 },
      { 'station_name': '汶水东路541弄', 'station_no': 7 },
      { 'station_name': '水电路1119弄水电公寓', 'station_no': 8 },
      { 'station_name': '水电路复旦宿舍小区对面', 'station_no': 9 },
      { 'station_name': '车站北路400弄', 'station_no': 10 },
      { 'station_name': '车站北路500弄', 'station_no': 11 },
      { 'station_name': '凉城华一小区对面', 'station_no': 12 },
      { 'station_name': '奎照路719弄近菜场', 'station_no': 13 },
      { 'station_name': '平型关路2199弄粤秀名邸近江场路', 'station_no': 14 },
      { 'station_name': '大润发到达时间', 'station_no': 15 },
      { 'station_name': '大润发出发时间', 'station_no': 16 }]
    },
    {
      'shuttle_lines': 8,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店3号线凉城二线',
      'shuttle_no': '1001_3',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '汶水路水电小区650弄', 'station_no': 2 },
      { 'station_name': '广灵四路280弄弄口', 'station_no': 3 },
      { 'station_name': '广灵四路368号快客便利', 'station_no': 4 },
      { 'station_name': '凉城路广中扩大小区', 'station_no': 5 },
      { 'station_name': '凉城路585弄对面东苑小区', 'station_no': 6 },
      { 'station_name': '车站南路407弄弄口', 'station_no': 7 },
      { 'station_name': '车站北路193号近758车站', 'station_no': 8 },
      { 'station_name': '新市南路1153弄近文治路路口', 'station_no': 9 },
      { 'station_name': '新市北路 工商银行', 'station_no': 10 },
      { 'station_name': '丰镇路16弄', 'station_no': 11 },
      { 'station_name': '丰镇路丰景湾名邸', 'station_no': 12 },
      { 'station_name': '丰镇路790号十四服装厂', 'station_no': 13 },
      { 'station_name': '广粤路良辰美景', 'station_no': 14 },
      { 'station_name': '广粤路1401弄胜利小区', 'station_no': 15 },
      { 'station_name': '大润发到达时间', 'station_no': 16 },
      { 'station_name': '大润发出发时间', 'station_no': 17 }]
    },
    {
      'shuttle_lines': 5,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '闸北店4号线共富泰和线',
      'shuttle_no': '1001_4',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '天极花园', 'station_no': 2 },
      { 'station_name': '泰和新城（邮局）', 'station_no': 3 },
      { 'station_name': '泰和新城（大洋小区）', 'station_no': 4 },
      { 'station_name': '泰和新城西小区3511弄', 'station_no': 5 },
      { 'station_name': '富弘苑门口', 'station_no': 6 },
      { 'station_name': '共富四村对面共富三村门口', 'station_no': 7 },
      { 'station_name': '共富路花园21世纪便利店', 'station_no': 8 },
      { 'station_name': '共富一村 共富二村门口', 'station_no': 9 },
      { 'station_name': '大润发到达时间', 'station_no': 10 },
      { 'station_name': '大润发出发时间', 'station_no': 11 }]
    },
    {
      'shuttle_lines': 13,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '闸北店5号线永和二线',
      'shuttle_no': '1001_5',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '万荣路1050弄万荣阳光苑', 'station_no': 2 },
      { 'station_name': '永和路近荣和园', 'station_no': 3 },
      { 'station_name': '万荣小区永和菜场', 'station_no': 4 },
      { 'station_name': '永和路580弄', 'station_no': 5 },
      { 'station_name': '永和路880弄永和雅园', 'station_no': 6 },
      { 'station_name': '高平路598弄阳城美景', 'station_no': 7 },
      { 'station_name': '平遥路永和家园', 'station_no': 8 },
      { 'station_name': '沪太支路561弄永和家园', 'station_no': 9 },
      { 'station_name': '交城路386弄盛世馨园', 'station_no': 10 },
      { 'station_name': '交城路永和二村', 'station_no': 11 },
      { 'station_name': '原平路918弄教师公寓', 'station_no': 12 },
      { 'station_name': '大润发到达时间', 'station_no': 13 },
      { 'station_name': '大润发出发时间', 'station_no': 14 }]
    },
    {
      'shuttle_lines': 5,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店6号线淞南华浜线',
      'shuttle_no': '1001_6',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '淞发路751终点站', 'station_no': 2 },
      { 'station_name': '淞发路淞良路路口', 'station_no': 3 },
      { 'station_name': '淞南路淞南四村近车站', 'station_no': 4 },
      { 'station_name': '华浜新村', 'station_no': 5 },
      { 'station_name': '张华浜20弄5号路口', 'station_no': 6 },
      { 'station_name': '华浜二村', 'station_no': 7 },
      { 'station_name': '淞发路鎏园小区', 'station_no': 8 },
      { 'station_name': '淞南路长宏新苑对面车站', 'station_no': 9 },
      { 'station_name': '长逸路淞南新五村', 'station_no': 10 },
      { 'station_name': '长逸路淞南六村15~60号对面', 'station_no': 11 },
      { 'station_name': '西塘桥站', 'station_no': 12 },
      { 'station_name': '淞南九村对面', 'station_no': 13 },
      { 'station_name': '新二路嘉骏花园', 'station_no': 14 },
      { 'station_name': '新二路183弄对面', 'station_no': 15 },
      { 'station_name': '大润发到达时间', 'station_no': 16 },
      { 'station_name': '大润发出发时间', 'station_no': 17 }]
    },
    {
      'shuttle_lines': 5,
      'shuttle_memos': ['运营时间：周二、四、六',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店7号线蕴川线',
      'shuttle_no': '1001_7',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '梅林路866弄宝虹水岸景苑', 'station_no': 2 },
      { 'station_name': '宝杨路宝启花园近3276号', 'station_no': 3 },
      { 'station_name': '宝杨路3184弄口', 'station_no': 4 },
      { 'station_name': '杨泰三村东区', 'station_no': 5 },
      { 'station_name': '杨泰路东方丽都对面', 'station_no': 6 },
      { 'station_name': '友谊路富杨路路口', 'station_no': 7 },
      { 'station_name': '松兰路万科四季花城门口', 'station_no': 8 },
      { 'station_name': '松兰路151号四季花城对面', 'station_no': 9 },
      { 'station_name': '杨泰路杨泰一村', 'station_no': 10 },
      { 'station_name': '杨鑫路五冶杨泰二村', 'station_no': 11 },
      { 'station_name': '杨鑫路杨泰二村西门', 'station_no': 12 },
      { 'station_name': '水产路梅林路近宝山一路公交站', 'station_no': 13 },
      { 'station_name': '蕴川路华馨苑', 'station_no': 14 },
      { 'station_name': '大润发到达时间', 'station_no': 15 },
      { 'station_name': '大润发出发时间', 'station_no': 16 }]
    },
    {
      'shuttle_lines': 10,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店8号线临汾曲沃线',
      'shuttle_no': '1001_8',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '临汾路1060弄近车站', 'station_no': 2 },
      { 'station_name': '曲沃路321弄对面', 'station_no': 3 },
      { 'station_name': '曲沃路373弄小区对面', 'station_no': 4 },
      { 'station_name': '三泉路兴泉小区对面近车站', 'station_no': 5 },
      { 'station_name': '三泉路1015弄共康前进公寓', 'station_no': 6 },
      { 'station_name': '共康五村', 'station_no': 7 },
      { 'station_name': '共康四村', 'station_no': 8 },
      { 'station_name': '共康三村', 'station_no': 9 },
      { 'station_name': '临汾路近教堂', 'station_no': 10 },
      { 'station_name': '临汾路1231弄', 'station_no': 11 },
      { 'station_name': '临汾路1105弄', 'station_no': 12 },
      { 'station_name': '曲沃路255弄', 'station_no': 13 },
      { 'station_name': '曲沃路79弄', 'station_no': 14 },
      { 'station_name': '大润发到达时间', 'station_no': 15 },
      { 'station_name': '大润发出发时间', 'station_no': 16 }]
    },
    {
      'shuttle_lines': 10,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店9号线彭浦五线',
      'shuttle_no': '1001_9',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '闻喜路闸北图书馆对面', 'station_no': 2 },
      { 'station_name': '闻喜路邮政门口', 'station_no': 3 },
      { 'station_name': '临汾路375弄临汾小区', 'station_no': 4 },
      { 'station_name': '阳曲路470弄570弄', 'station_no': 5 },
      { 'station_name': '保德路云会曲当行', 'station_no': 6 },
      { 'station_name': '保德路662弄保平小区', 'station_no': 7 },
      { 'station_name': '保德路1120弄近760车站', 'station_no': 8 },
      { 'station_name': '保德路1238弄艺康苑', 'station_no': 9 },
      { 'station_name': '保德路1316弄好德便利店', 'station_no': 10 },
      { 'station_name': '三泉路三泉前进公寓', 'station_no': 11 },
      { 'station_name': '三泉路517弄', 'station_no': 12 },
      { 'station_name': '闻喜路1110弄对面', 'station_no': 13 },
      { 'station_name': '间喜路935弄971弄近862车站', 'station_no': 14 },
      { 'station_name': '大润发到达时间', 'station_no': 15 },
      { 'station_name': '大润发出发时间', 'station_no': 16 }]
    },
    {
      'shuttle_lines': 9,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店10号线江杨高境线',
      'shuttle_no': '1001_10',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '江杨南路55弄凉城路东门', 'station_no': 2 },
      { 'station_name': '虹北公寓凉城路边门', 'station_no': 3 },
      { 'station_name': '云西路219弄香梅苑', 'station_no': 4 },
      { 'station_name': '高境路杰圣家园对面', 'station_no': 5 },
      { 'station_name': '高境路477弄恒高家园', 'station_no': 6 },
      { 'station_name': '恒高路127弄高杨佳苑', 'station_no': 7 },
      { 'station_name': '江杨南路466弄和源名城', 'station_no': 8 },
      { 'station_name': '虹湾路55弄金枫里对面', 'station_no': 9 },
      { 'station_name': '平型关路2199弄粤秀名邸近江场路', 'station_no': 10 },
      { 'station_name': '大润发到达时间', 'station_no': 11 },
      { 'station_name': '大润发出发时间', 'station_no': 12 }]
    },
    {
      'shuttle_lines': 8,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店11号线广灵水电线',
      'shuttle_no': '1001_11',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '广粤路439弄弄口', 'station_no': 2 },
      { 'station_name': '株州路388弄建明花苑', 'station_no': 3 },
      { 'station_name': '株州路300弄三湘花苑', 'station_no': 4 },
      { 'station_name': '同心路1128弄口春满园B区对面', 'station_no': 5 },
      { 'station_name': '同心路1045弄宝苑小区', 'station_no': 6 },
      { 'station_name': '水电路何家宅小区', 'station_no': 7 },
      { 'station_name': '水电路36号近875车站', 'station_no': 8 },
      { 'station_name': '水电路583弄', 'station_no': 9 },
      { 'station_name': '广灵二路商洛小区对面近745车站', 'station_no': 10 },
      { 'station_name': '广灵四路广灵二村对面广灵一村近车站', 'station_no': 11 },
      { 'station_name': '广灵四路280弄弄口', 'station_no': 12 },
      { 'station_name': '广灵四路368号快客便利店', 'station_no': 13 },
      { 'station_name': '广灵四路572弄秀苑小区', 'station_no': 14 },
      { 'station_name': '江杨路海虹欣苑1067弄-1099弄', 'station_no': 15 },
      {
        'station_name': '平型关路2199弄粤秀名邸近江场路路口',
        'station_no': 16
      },
      { 'station_name': '大润发到达时间', 'station_no': 17 },
      { 'station_name': '大润发出发时间', 'station_no': 18 }]
    },
    {
      'shuttle_lines': 10,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店12号线彭浦东环线',
      'shuttle_no': '1001_12',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '闻喜路邮政门口', 'station_no': 2 },
      { 'station_name': '闻喜路555弄弄口', 'station_no': 3 },
      { 'station_name': '闻喜路251弄弄口', 'station_no': 4 },
      { 'station_name': '汾西路260弄弄口', 'station_no': 5 },
      { 'station_name': '阳曲路670弄新昌润', 'station_no': 6 },
      { 'station_name': '阳曲路781弄', 'station_no': 7 },
      { 'station_name': '成投世纪名城', 'station_no': 8 },
      { 'station_name': '共和三村', 'station_no': 9 },
      { 'station_name': '景凤路701终点站', 'station_no': 10 },
      { 'station_name': '岭南路（近岭南人家）', 'station_no': 11 },
      { 'station_name': '岭南路236弄对面', 'station_no': 12 },
      { 'station_name': '大润发到达时间', 'station_no': 13 },
      { 'station_name': '大润发出发时间', 'station_no': 14 }]
    },
    {
      'shuttle_lines': 9,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店13号线彭浦西环线',
      'shuttle_no': '1001_13',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '保德路三泉公园', 'station_no': 2 },
      { 'station_name': '保德路1316弄', 'station_no': 3 },
      { 'station_name': '三泉路银都幼儿园', 'station_no': 4 },
      { 'station_name': '三泉路852终点站近野桥集贸市场', 'station_no': 5 },
      { 'station_name': '三泉路共康六村', 'station_no': 6 },
      { 'station_name': '三泉路1858弄宝晨共和家园一号门', 'station_no': 7 },
      { 'station_name': '三泉路1858弄宝晨共和家园二号门', 'station_no': 8 },
      { 'station_name': '新梅绿岛苑场北路长临路路口', 'station_no': 9 },
      { 'station_name': '长临路九英里弄口', 'station_no': 10 },
      { 'station_name': '屹立家园', 'station_no': 11 },
      { 'station_name': '共康八村', 'station_no': 12 },
      { 'station_name': '共康四村', 'station_no': 13 },
      { 'station_name': '共康三村', 'station_no': 14 },
      { 'station_name': '临汾路近教堂', 'station_no': 15 },
      { 'station_name': '临汾路253终点站对面', 'station_no': 16 },
      { 'station_name': '大润发到达时间', 'station_no': 17 },
      { 'station_name': '大润发出发时间', 'station_no': 18 }]
    },
    {
      'shuttle_lines': 7,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店14号线幸福海鹰线',
      'shuttle_no': '1001_14',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '南大路96弄', 'station_no': 2 },
      { 'station_name': '南大路138弄', 'station_no': 3 },
      { 'station_name': '南大路190弄', 'station_no': 4 },
      { 'station_name': '环镇北路600弄', 'station_no': 5 },
      { 'station_name': '环镇北路400弄', 'station_no': 6 },
      { 'station_name': '场联路乾心园', 'station_no': 7 },
      { 'station_name': '乾溪路151弄', 'station_no': 8 },
      { 'station_name': '场中路少年村路110车站', 'station_no': 9 },
      { 'station_name': '场中路海鹰小区3300弄110车站', 'station_no': 10 },
      { 'station_name': '场中路幸福二村近工商银行', 'station_no': 11 },
      { 'station_name': '场中路幸福一村', 'station_no': 12 },
      { 'station_name': '大润发到达时间', 'station_no': 13 },
      { 'station_name': '大润发出发时间', 'station_no': 14 }]
    },
    {
      'shuttle_lines': 10,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店15号线彭浦中环线',
      'shuttle_no': '1001_15',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '汾西路815弄', 'station_no': 2 },
      { 'station_name': '汾西路671弄', 'station_no': 3 },
      { 'station_name': '汾西路377号上海老味道站', 'station_no': 4 },
      { 'station_name': '汾西路261弄', 'station_no': 5 },
      { 'station_name': '汾西路87弄', 'station_no': 6 },
      { 'station_name': '汾西路临汾花园对面', 'station_no': 7 },
      { 'station_name': '临汾路阳曲小区', 'station_no': 8 },
      { 'station_name': '阳曲路670弄新昌润', 'station_no': 9 },
      { 'station_name': '阳曲路781弄对面', 'station_no': 10 },
      { 'station_name': '景凤路近701终点站', 'station_no': 11 },
      { 'station_name': '保德路彭浦实验小学近812车站', 'station_no': 12 },
      { 'station_name': '大润发到达时间', 'station_no': 13 },
      { 'station_name': '大润发出发时间', 'station_no': 14 }]
    },
    {
      'shuttle_lines': 13,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店16号线永和一线',
      'shuttle_no': '1001_16',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '万荣路1050弄万荣阳光苑', 'station_no': 2 },
      { 'station_name': '永和路（近荣和园）', 'station_no': 3 },
      { 'station_name': '万荣小区（永和菜场）', 'station_no': 4 },
      { 'station_name': '永和路580弄', 'station_no': 5 },
      { 'station_name': '原平路383弄永和丽园', 'station_no': 6 },
      { 'station_name': '阳城路101弄对面', 'station_no': 7 },
      { 'station_name': '原平路528弄物华园', 'station_no': 8 },
      { 'station_name': '原平路758弄永和东村', 'station_no': 9 },
      { 'station_name': '原平路永和三村对面教师公寓', 'station_no': 10 },
      { 'station_name': '大润发到达时间', 'station_no': 11 },
      { 'station_name': '大润发出发时间', 'station_no': 12 }]
    },
    {
      'shuttle_lines': 9,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店17号线彭浦四线',
      'shuttle_no': '1001_17',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '共康路共康四村北门', 'station_no': 2 },
      { 'station_name': '长临路共康八村对面近公交站', 'station_no': 3 },
      { 'station_name': '长临路屹立家园对面近公交站', 'station_no': 4 },
      { 'station_name': '长临路1318弄九英里对面', 'station_no': 5 },
      { 'station_name': '场北路399弄新绿岛苑', 'station_no': 6 },
      { 'station_name': '场北路551弄中环国际公寓', 'station_no': 7 },
      { 'station_name': '大康路891弄共康雅苑', 'station_no': 8 },
      { 'station_name': '花园宅路52弄共康雅苑', 'station_no': 9 },
      { 'station_name': '场中路3300弄对面近110车站', 'station_no': 10 },
      { 'station_name': '少年村路龙馨嘉园', 'station_no': 11 },
      { 'station_name': '少年村路白玉兰馨园对面', 'station_no': 12 },
      { 'station_name': '原平路成亿花园', 'station_no': 13 },
      { 'station_name': '大润发到达时间', 'station_no': 14 },
      { 'station_name': '大润发出发时间', 'station_no': 15 }]
    },
    {
      'shuttle_lines': 8,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店18号线爱辉西环线',
      'shuttle_no': '1001_18',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '爱辉路泗塘二三村', 'station_no': 2 },
      { 'station_name': '呼玛路呼玛二村6号-305号', 'station_no': 3 },
      { 'station_name': '呼玛路龙缘花园东区对面', 'station_no': 4 },
      { 'station_name': '呼兰路呼玛五村对面', 'station_no': 5 },
      { 'station_name': '通河路呼玛三村', 'station_no': 6 },
      { 'station_name': '通河路通河一村对面', 'station_no': 7 },
      { 'station_name': '通河路通河三小对面', 'station_no': 8 },
      { 'station_name': '共江路通河七村', 'station_no': 9 },
      { 'station_name': '共江路通河六村对面', 'station_no': 10 },
      { 'station_name': '锦辉绿园', 'station_no': 11 },
      { 'station_name': '岭南路岭南雅苑对面', 'station_no': 12 },
      { 'station_name': '岭南路高境七幼', 'station_no': 13 },
      { 'station_name': '大润发到达时间', 'station_no': 14 },
      { 'station_name': '大润发出发时间', 'station_no': 15 }]
    },
    {
      'shuttle_lines': 8,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店19号线爱辉东环线',
      'shuttle_no': '1001_19',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '爱辉路泗塘一村近良友便利店', 'station_no': 2 },
      { 'station_name': '虎林路800弄富浩花园对面', 'station_no': 3 },
      { 'station_name': '呼兰路538号富浩花园对面', 'station_no': 4 },
      { 'station_name': '呼兰路呼玛四村', 'station_no': 5 },
      { 'station_name': '通河路呼玛三村', 'station_no': 6 },
      { 'station_name': '呼玛路646号通河一村', 'station_no': 7 },
      { 'station_name': '呼玛路呼玛一村', 'station_no': 8 },
      { 'station_name': '虎林中学对面', 'station_no': 9 },
      { 'station_name': '虎林路泗塘二三村', 'station_no': 10 },
      { 'station_name': '虎林路泗塘六村', 'station_no': 11 },
      { 'station_name': '虎林路泗塘八村', 'station_no': 12 },
      { 'station_name': '阳曲路1111号美树铭家', 'station_no': 13 },
      { 'station_name': '共和四村26号高境七幼', 'station_no': 14 },
      { 'station_name': '岭南路50弄.100弄对面', 'station_no': 15 },
      { 'station_name': '大润发到达时间', 'station_no': 16 },
      { 'station_name': '大润发出发时间', 'station_no': 17 }]
    },
    {
      'shuttle_lines': 5,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！\r\n'],
      'shuttle_name': '闸北店20号线锦秋祁连线',
      'shuttle_no': '1001_20',
      'shuttle_stations': [{ 'station_name': '站点/班次', 'station_no': 1 },
      { 'station_name': '祁连山路祁连四村', 'station_no': 2 },
      { 'station_name': '祁华路58弄封润华庭', 'station_no': 3 },
      { 'station_name': '祁华路218弄封润华庭', 'station_no': 4 },
      { 'station_name': '祁华路300弄江枫景苑', 'station_no': 5 },
      { 'station_name': '瑞丰路1588弄丰宝苑', 'station_no': 6 },
      { 'station_name': '聚丰园路祁连欣苑', 'station_no': 7 },
      { 'station_name': '祁连二村对面锦龙苑', 'station_no': 8 },
      { 'station_name': '祁连山路祁连一村', 'station_no': 9 },
      { 'station_name': '上大聚丰园环镇北路1258弄', 'station_no': 10 },
      { 'station_name': '慧华苑南门对面', 'station_no': 11 },
      { 'station_name': '环镇北路600弄', 'station_no': 12 },
      { 'station_name': '环镇北路400弄', 'station_no': 13 },
      { 'station_name': '场联路乾心园对面', 'station_no': 14 },
      { 'station_name': '乾溪路151弄', 'station_no': 15 },
      { 'station_name': '沪太支路899弄中星馨恒苑对面', 'station_no': 16 },
      { 'station_name': '大润发到达时间', 'station_no': 17 },
      { 'station_name': '大润发出发时间', 'station_no': 18 }]
    }]
  } else if (storeNo === 1063){
    lines = [{
      'shuttle_lines': 12,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '三林店1号线海阳线',
      'shuttle_no': '1063_1',
      'shuttle_stations': [
      { 'station_name': '981路终点站对面', 'station_no': 2 },
      { 'station_name': '海阳路日月新殿', 'station_no': 3 },
      { 'station_name': '海阳路金苹果花园', 'station_no': 4 },
      { 'station_name': '海阳路东旺名苑', 'station_no': 5 },
      { 'station_name': '海阳路山水苑', 'station_no': 6 },
      { 'station_name': '海阳路香樟苑', 'station_no': 7 },
      { 'station_name': '云台路836号对面(云台路上浜路口)', 'station_no': 8 },
      { 'station_name': '杨思路东方悦居', 'station_no': 9 },
      { 'station_name': '杨思路申江豪城', 'station_no': 10 },
      { 'station_name': '杨思路501号', 'station_no': 11 },
      { 'station_name': '灵岩南路196号', 'station_no': 12 },
      { 'station_name': '板泉路南杨小区', 'station_no': 13 }
      ]
    },
    {
      'shuttle_lines': 12,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '三林店2号线凌兆线',
      'shuttle_no': '1063_2',
      'shuttle_stations': [
      { 'station_name': '凌兆路285弄边门', 'station_no': 2 },
      { 'station_name': '凌兆七村（凌兆第七居委会）', 'station_no': 3 },
      { 'station_name': '凌兆路500弄门口', 'station_no': 4 },
      { 'station_name': '凌兆路608弄门口', 'station_no': 5 },
      { 'station_name': '凌兆路726弄门口', 'station_no': 6 },
      { 'station_name': '上南路千里香馄饨门口', 'station_no': 7 },
      { 'station_name': '三林路788弄对面', 'station_no': 8 },
      { 'station_name': '三林路675弄丹桂小区门口', 'station_no': 9 },
      { 'station_name': '三林路519弄玉兰苑门口', 'station_no': 10 },
      { 'station_name': '凌兆路256弄对面（好德门口）', 'station_no': 11 },
      { 'station_name': '凌兆路127弄 岭南苑', 'station_no': 12 },
      { 'station_name': '凌兆路88弄对面华光苑', 'station_no': 13 },
      { 'station_name': '上浦路36弄门口', 'station_no': 14 },
      { 'station_name': '凌兆十一、十二村门口', 'station_no': 15 },
      { 'station_name': '上浦路202弄门口', 'station_no': 16 }]
    },
    {
      'shuttle_lines': 9,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '三林店3号线三鲁线',
      'shuttle_no': '1063_3',
      'shuttle_stations': [
      { 'station_name': '绿波家 盛世南苑（和炯路104号）', 'station_no': 2 },
      { 'station_name': '和炯路201号联华超市对面', 'station_no': 3 },
      { 'station_name': '德康苑501弄对面', 'station_no': 4 },
      { 'station_name': '瑞康苑601弄对面', 'station_no': 5 },
      { 'station_name': '东方康德971弄', 'station_no': 6 },
      { 'station_name': '和佳路       东方康德家园', 'station_no': 7 },
      { 'station_name': '林展路267弄37号边门', 'station_no': 8 },
      { 'station_name': '三舒路城林美苑', 'station_no': 9 },
      { 'station_name': '士韵家园 和融路55弄', 'station_no': 10 },
      { 'station_name': '三彩路166弄', 'station_no': 11 }]
    },
    {
      'shuttle_lines': 8,
      'shuttle_memos': ['运营时间：周一、三、五、日运行。',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '三林店4号线齐河路',
      'shuttle_no': '1063_4',
      'shuttle_stations': [
      { 'station_name': '成山小区（东明路668弄门口）', 'station_no': 2 },
      { 'station_name': '邹平路1675弄', 'station_no': 3 },
      { 'station_name': '南码头路1696弄对面', 'station_no': 4 },
      { 'station_name': '南码头路1621弄', 'station_no': 5 },
      { 'station_name': '南码头路1521弄', 'station_no': 6 },
      { 'station_name': '昌里东路411弄', 'station_no': 7 },
      { 'station_name': '昌里东路320弄对面', 'station_no': 8 },
      { 'station_name': '齐七小区边门（东明路昌里东路）', 'station_no': 9 },
      { 'station_name': '都市庭院对面', 'station_no': 10 },
      { 'station_name': '上南花苑', 'station_no': 11 },
      { 'station_name': '云台大厦（云台路145弄）', 'station_no': 12 },
      { 'station_name': '上钢九十村对面（济阳新村门口)', 'station_no': 13 },
      { 'station_name': '西营路114弄门口', 'station_no': 14 },
      { 'station_name': '德州四村对面（成山路24弄）', 'station_no': 15 }]
    },
    {
      'shuttle_lines': 11,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '三林店5号线昌里西线',
      'shuttle_no': '1063_5',
      'shuttle_stations': [
      { 'station_name': '德州路300弄门口', 'station_no': 2 },
      { 'station_name': '德六新村（德州路246弄）', 'station_no': 3 },
      { 'station_name': '德州路230弄门口', 'station_no': 4 },
      { 'station_name': '上南十一村（德州路150弄）', 'station_no': 5 },
      { 'station_name': '中星云庭（德州路60弄）', 'station_no': 6 },
      { 'station_name': '上南十二村（德州路20弄）', 'station_no': 7 },
      { 'station_name': '云台路461号门口', 'station_no': 8 },
      { 'station_name': '云台小区（云莲路边门）对面', 'station_no': 9 },
      { 'station_name': '昌里花园（昌里东路71弄）', 'station_no': 10 },
      { 'station_name': '上南六村（昌里路91号）门口', 'station_no': 11 },
      { 'station_name': '上南二村（昌里路167弄）门口', 'station_no': 12 },
      { 'station_name': '世博家园实验小学对面', 'station_no': 13 },
      { 'station_name': '上钢五村（昌里路360弄）对门', 'station_no': 14 },
      { 'station_name': '长清路136弄门口', 'station_no': 15 }]
    },
    {
      'shuttle_lines': 10,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '三林店6号线永泰线',
      'shuttle_no': '1063_6',
      'shuttle_stations': [{ 'station_name': '永泰路136弄门口', 'station_no': 2 },
      { 'station_name': '永泰路258弄门口', 'station_no': 3 },
      { 'station_name': '永泰路468弄门口', 'station_no': 4 },
      { 'station_name': '永泰花园(永泰路630弄)门口', 'station_no': 5 },
      { 'station_name': '品华苑(永泰路)门口', 'station_no': 6 },
      { 'station_name': '品珍苑(环林西路579弄)门口', 'station_no': 7 },
      { 'station_name': '红枫苑(环林西路848弄)门口', 'station_no': 8 },
      { 'station_name': '杉林新苑A区(环林东路875弄)门口', 'station_no': 9 },
      { 'station_name': '杉林新苑B区(环林东路799弄)门口', 'station_no': 10 },
      { 'station_name': '环林东路安盛街口对面', 'station_no': 11 },
      { 'station_name': '金禾新苑门口', 'station_no': 12 },
      { 'station_name': '金橘新苑(尚博路650弄)对面', 'station_no': 13 },
      { 'station_name': '尚博路647号好德便利店门口', 'station_no': 14 },
      { 'station_name': '三林苑（三林路出口)对面', 'station_no': 15 },
      { 'station_name': '翠竹苑门口', 'station_no': 16 },
      { 'station_name': '金谊河畔595弄口', 'station_no': 17 },
      { 'station_name': '永泰路468弄门口', 'station_no': 18 },
      { 'station_name': '永泰路258弄门口', 'station_no': 19 },
      { 'station_name': '永泰路136弄门口', 'station_no': 20 }]
    },
    {
      'shuttle_lines': 9,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '三林店7号线南码头线',
      'shuttle_no': '1063_7',
      'shuttle_stations': [{ 'station_name': '昌五小区(昌里东路650弄)门口', 'station_no': 2 },
      { 'station_name': '浦三路813号门口', 'station_no': 3 },
      { 'station_name': '浦三路721号门口', 'station_no': 4 },
      { 'station_name': '浦三路645号(伍缘便利店门口)', 'station_no': 5 },
      { 'station_name': '临沂八村（兰陵路23弄出口)', 'station_no': 6 },
      { 'station_name': '临沂七村(临沂路101弄)对面', 'station_no': 7 },
      { 'station_name': '临沂二村门口(近东方书报亭)', 'station_no': 8 },
      { 'station_name': '临沂五村(南码头路568号)门口 ', 'station_no': 9 },
      { 'station_name': '博文家园(南码头路1120弄)', 'station_no': 10 },
      { 'station_name': '齐二小区(南码头路1186弄)', 'station_no': 11 },
      { 'station_name': '紫竹馨苑(南码头路1378弄)门口', 'station_no': 12 }]
    },
    {
      'shuttle_lines': 8,
      'shuttle_memos': ['运营时间：周二、四、六运行。',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '三林店8号线绿林下南线',
      'shuttle_no': '1063_8',
      'shuttle_stations': [{ 'station_name': '翰林园（杨南路洪山路）', 'station_no': 2 },
      { 'station_name': '杨南路1168弄（都林嘉园南苑）', 'station_no': 3 },
      { 'station_name': '翰城国际（云台路1000弄）', 'station_no': 4 },
      { 'station_name': '博学家园（高青路）', 'station_no': 5 },
      { 'station_name': '高青路2878弄万科新里程', 'station_no': 6 },
      { 'station_name': '三林世博家园（高青路560弄门口）', 'station_no': 7 },
      { 'station_name': '世博家园实验小学门口', 'station_no': 8 },
      { 'station_name': '东书房路联华超市门口', 'station_no': 9 },
      { 'station_name': '南新六村（下南路500弄对面）', 'station_no': 10 },
      { 'station_name': '文汇小区（下南路320弄门口）', 'station_no': 11 },
      { 'station_name': '绿星小区（下南路225弄门口）', 'station_no': 12 },
      { 'station_name': '绿林路320弄门口', 'station_no': 13 },
      { 'station_name': '绿川新苑（绿林路52弄门口）', 'station_no': 14 },
      { 'station_name': '博华路999弄/980弄门口', 'station_no': 15 },
      { 'station_name': '南新三村（三里路339弄对面）', 'station_no': 16 },
      { 'station_name': '文汇小区（下南路370弄边门)', 'station_no': 17 },
      { 'station_name': '新浦路251弄对面', 'station_no': 18 },
      { 'station_name': '三林世博家园（板泉路2101弄）', 'station_no': 19 },
      { 'station_name': '科勒门口（板泉路2000号）', 'station_no': 20 },
      { 'station_name': '万科新里程', 'station_no': 21 },
      {
        'station_name': '博学家园高青路出口（康健运动陶瓷对面）',
        'station_no': 22
      }]
    },
    {
      'shuttle_lines': 10,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '三林店9号线恒大耀华线',
      'shuttle_no': '1063_9',
      'shuttle_stations': [{ 'station_name': '板泉路西营南路三杨新村路口', 'station_no': 2 },
      {
        'station_name': '公交84路986路(杨思路西营南路站)对面',
        'station_no': 3
      },
      { 'station_name': '德州路420弄(济阳一村)', 'station_no': 4 },
      { 'station_name': '西营路111号门口好德便利', 'station_no': 5 },
      { 'station_name': '西营路35号(上钢新村)门口', 'station_no': 6 },
      { 'station_name': '耀华路400弄门口', 'station_no': 7 },
      { 'station_name': '耀华路200弄门口', 'station_no': 8 },
      { 'station_name': '耀华路32号门口', 'station_no': 9 },
      { 'station_name': '上南一村门口', 'station_no': 10 },
      { 'station_name': '洪山路121弄(上南五村)对面', 'station_no': 11 },
      { 'station_name': '洪山路168号门口(社保中心)', 'station_no': 12 },
      { 'station_name': '德州一村门口(上南出口)', 'station_no': 13 },
      { 'station_name': '杨思新村门口(影剧院对面)', 'station_no': 14 },
      { 'station_name': '杨新路198弄门口', 'station_no': 15 },
      { 'station_name': '恒大华城门口(长清路杨新路出口)', 'station_no': 16 }]
    },
    {
      'shuttle_lines': 6,
      'shuttle_memos': ['运营时间：周二、四、六运行。',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！'],
      'shuttle_name': '三林店10号线浦江线',
      'shuttle_no': '1063_10',
      'shuttle_stations': [{ 'station_name': '一品漫城', 'station_no': 2 },
      { 'station_name': '川浦线“江月路浦驰路”车站附近', 'station_no': 3 },
      { 'station_name': '北江燕路338弄边门口（五街坊对面）', 'station_no': 4 },
      { 'station_name': '浦驰路345弄门口', 'station_no': 5 },
      { 'station_name': '浦驰路235弄门口', 'station_no': 6 },
      { 'station_name': '十四街浦申路边门门口', 'station_no': 7 },
      { 'station_name': '联航路2165弄边门', 'station_no': 8 },
      { 'station_name': '联航路2015弄十四街坊正门', 'station_no': 9 },
      { 'station_name': '江汉路99弄对面', 'station_no': 10 },
      { 'station_name': '江汉路200弄', 'station_no': 11 },
      { 'station_name': '浦秀路48弄门口', 'station_no': 12 },
      { 'station_name': '浦秀路220弄门口', 'station_no': 13 },
      { 'station_name': '浦秀路360弄', 'station_no': 14 },
      { 'station_name': '浦秀路518弄门口', 'station_no': 15 },
      { 'station_name': '浦秀路598弄门口', 'station_no': 16 }]
    },
    {
      'shuttle_lines': 11,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！ '],
      'shuttle_name': '三林店11号线昌里西线',
      'shuttle_no': '1063_11',
      'shuttle_stations': [{ 'station_name': '德州路300弄门口', 'station_no': 2 },
      { 'station_name': '德六新村（德州路246弄）', 'station_no': 3 },
      { 'station_name': '德州路230弄门口', 'station_no': 4 },
      { 'station_name': '上南十一村（德州路150弄）', 'station_no': 5 },
      { 'station_name': '中星云庭（德州路60弄）', 'station_no': 6 },
      { 'station_name': '上南十二村（德州路20弄）', 'station_no': 7 },
      { 'station_name': '云台路461号门口', 'station_no': 8 },
      { 'station_name': '云台小区（云莲路边门）对面', 'station_no': 9 },
      { 'station_name': '昌里花园（昌里东路71弄）', 'station_no': 10 },
      { 'station_name': '上南六村（昌里路91号）门口', 'station_no': 11 },
      { 'station_name': '上南二村（昌里路167弄）门口', 'station_no': 12 },
      { 'station_name': '世博家园实验小学对面', 'station_no': 13 },
      { 'station_name': '上钢五村（昌里路360弄）对门', 'station_no': 14 },
      { 'station_name': '长清路136弄门口', 'station_no': 15 }]
    },
    {
      'shuttle_lines': 5,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！ '],
      'shuttle_name': '三林店12号线龙华线',
      'shuttle_no': '1063_12',
      'shuttle_stations': [{ 'station_name': '龙兆苑(龙华路3208弄）', 'station_no': 2 },
      { 'station_name': '周家湾3号门（龙华路3100号）', 'station_no': 3 },
      { 'station_name': '盛大花园小学门口(龙华路2588号', 'station_no': 4 },
      { 'station_name': '龙华路2506/  2508号门口', 'station_no': 5 },
      { 'station_name': '徐汇临江豪园（宛平南路921弄)', 'station_no': 6 },
      { 'station_name': '汇丰大药房门口（中山南二路922号）', 'station_no': 7 },
      { 'station_name': '中山南二路950/960弄', 'station_no': 8 },
      { 'station_name': '宛南六村对面', 'station_no': 9 },
      { 'station_name': '龙华新村对面', 'station_no': 10 },
      { 'station_name': '强生花苑（天钥桥路1162号）', 'station_no': 11 },
      { 'station_name': '龙水北路960弄', 'station_no': 12 },
      { 'station_name': '龙华西路81弄', 'station_no': 13 },
      { 'station_name': '44路终点站对面(龙华西路)', 'station_no': 14 },
      { 'station_name': '丰谷路205弄门口', 'station_no': 15 }]
    },
    {
      'shuttle_lines': 9,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！ '],
      'shuttle_name': '三林店13号线三鲁B线',
      'shuttle_no': '1063_13',
      'shuttle_stations': [{
        'station_name': '绿波家园     盛世南苑   （和炯路104号）',
        'station_no': 2
      },
      { 'station_name': '和炯路201号联华超市对面', 'station_no': 3 },
      { 'station_name': '德康苑501弄对面', 'station_no': 4 },
      { 'station_name': '瑞康苑601弄对面', 'station_no': 5 },
      { 'station_name': '东方康德971弄', 'station_no': 6 },
      { 'station_name': '和佳路 东方康德家园', 'station_no': 7 },
      { 'station_name': '林展路267弄37号边门', 'station_no': 8 },
      { 'station_name': '三舒路 城林美苑', 'station_no': 9 },
      { 'station_name': '士韵家园和融路55弄', 'station_no': 10 },
      { 'station_name': '三彩路166弄', 'station_no': 11 }]
    },
    {
      'shuttle_lines': 9,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！ '],
      'shuttle_name': '三林店14号线龙南新村一线',
      'shuttle_no': '1063_14',
      'shuttle_stations': [{ 'station_name': '园南新村（一号门）', 'station_no': 2 },
      { 'station_name': '园南新村（四号门）', 'station_no': 3 },
      { 'station_name': '天然居（百色路228弄-238弄）对面', 'station_no': 4 },
      { 'station_name': '园林格兰云天大酒店对面', 'station_no': 5 },
      { 'station_name': '虹飞图文(百色路  31号)', 'station_no': 6 },
      { 'station_name': '樟树苑968门口', 'station_no': 7 },
      { 'station_name': '绿色新村对面（龙水南路385弄）', 'station_no': 8 },
      { 'station_name': '龙南五村对面', 'station_no': 9 },
      { 'station_name': '龙南三村四村', 'station_no': 10 },
      { 'station_name': '誉仁家园', 'station_no': 11 },
      { 'station_name': '龙南五村七村（五缘店对面）', 'station_no': 12 }]
    },
    {
      'shuttle_lines': 7,
      'shuttle_memos': ['运营时间：周一、三、五、日运行。',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！ '],
      'shuttle_name': '三林店15号线浦东南路线',
      'shuttle_no': '1063_15',
      'shuttle_stations': [{ 'station_name': '耀华路500弄', 'station_no': 2 },
      { 'station_name': '耀华路400弄', 'station_no': 3 },
      { 'station_name': '耀华路32弄', 'station_no': 4 },
      { 'station_name': '上南一村门口', 'station_no': 5 },
      { 'station_name': '浦东南路4711号', 'station_no': 6 },
      { 'station_name': '浦东南路390弄博文园', 'station_no': 7 },
      { 'station_name': '港机新村（1-78号）', 'station_no': 8 },
      { 'station_name': '银河640路车站（浦南医院站）', 'station_no': 9 },
      { 'station_name': '工商银行门口', 'station_no': 10 },
      { 'station_name': '南码头路55号', 'station_no': 11 },
      { 'station_name': '微山二村', 'station_no': 12 },
      { 'station_name': '海运新村', 'station_no': 13 },
      { 'station_name': '浦东南路2244弄', 'station_no': 14 },
      { 'station_name': '胶南小区', 'station_no': 15 },
      { 'station_name': '雪野新村门口', 'station_no': 16 },
      { 'station_name': '浦东南路 4800  弄', 'station_no': 17 },
      { 'station_name': '上南花城门口', 'station_no': 18 },
      { 'station_name': '新世纪花苑(一期)', 'station_no': 19 },
      { 'station_name': '联城花苑', 'station_no': 20 }]
    },
    {
      'shuttle_lines': 7,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！ '],
      'shuttle_name': '三林店16号线龙南新村二线',
      'shuttle_no': '1063_16',
      'shuttle_stations': [{ 'station_name': '园南新村（一号门）', 'station_no': 2 },
      { 'station_name': '园南新村（四号门）', 'station_no': 3 },
      { 'station_name': '虹飞图文(百色路  31号)', 'station_no': 4 },
      { 'station_name': '喜泰支路151弄(1-9号)门口', 'station_no': 5 },
      { 'station_name': '龙水南路358弄(1-5号)门口', 'station_no': 6 },
      { 'station_name': '绿色新村对面（龙水南路385弄）', 'station_no': 7 },
      { 'station_name': '长峰小区（天钥桥南路1188弄）门口', 'station_no': 8 },
      { 'station_name': '滨江小区（天钥桥南路1249弄）对面', 'station_no': 9 },
      {
        'station_name': '龙南公寓（龙水南路269弄2-6号）门口',
        'station_no': 10
      },
      { 'station_name': '龙南三村四村', 'station_no': 11 },
      { 'station_name': '龙南五村七村（五缘店对面）', 'station_no': 12 },
      { 'station_name': '聚龙苑（黄石路18弄）对面', 'station_no': 13 },
      { 'station_name': '石龙路109号', 'station_no': 14 }]
    },
    {
      'shuttle_lines': 7,
      'shuttle_memos': ['运营时间：周一至周日',
        '乘客说明：请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！ '],
      'shuttle_name': '三林店17号线桂林线A线',
      'shuttle_no': '1063_17',
      'shuttle_stations': [{ 'station_name': '寿益坊(桂林西街)', 'station_no': 3 },
      { 'station_name': '寿祥坊桂林西街', 'station_no': 4 },
      { 'station_name': '寿山坊桂林西街', 'station_no': 5 },
      { 'station_name': '康强坊桂林东街', 'station_no': 6 },
      { 'station_name': '康乐小区桂林东街', 'station_no': 7 },
      { 'station_name': '长海坊桂林西街', 'station_no': 8 },
      { 'station_name': '长虹坊桂林西街', 'station_no': 9 },
      { 'station_name': '长丰坊', 'station_no': 10 },
      { 'station_name': '茶花园', 'station_no': 11 },
      { 'station_name': '百合花园', 'station_no': 12 },
      { 'station_name': '月季园', 'station_no': 13 },
      { 'station_name': '紫藤苑', 'station_no': 14 },
      { 'station_name': '桂花园', 'station_no': 15 }]
    },
    {
      'shuttle_lines': 7,
      'shuttle_memos': ['运营时间：周一至周日  ',
        '乘客说明： 请您务必提前10分钟至上述站点候车，如遇天气等异常情况影响而误点，敬请各位顾客多多谅解！  '],
      'shuttle_name': '三林店17号线桂林线B线',
      'shuttle_no': '1063_18',
      'shuttle_stations': [{ 'station_name': '三林店发车', 'station_no': 2 },
      { 'station_name': '寿益坊(桂林西街)', 'station_no': 3 },
      { 'station_name': '寿祥坊桂林西街', 'station_no': 4 },
      { 'station_name': '寿山坊桂林西街', 'station_no': 5 },
      { 'station_name': '康强坊桂林东街', 'station_no': 6 },
      { 'station_name': '康乐小区桂林东街', 'station_no': 7 },
      { 'station_name': '长海坊桂林西街', 'station_no': 8 },
      { 'station_name': '长虹坊桂林西街', 'station_no': 9 },
      { 'station_name': '长丰坊', 'station_no': 10 },
      { 'station_name': '茶花园', 'station_no': 11 },
      { 'station_name': '百合花园', 'station_no': 12 },
      { 'station_name': '月季园', 'station_no': 13 },
      { 'station_name': '紫藤苑', 'station_no': 14 },
      { 'station_name': '桂花园', 'station_no': 15 }]
    }]
  }
  return lines
}

module.exports = {
  getAllProvince: getAllProvince,
  getCurrentProvince: getCurrentProvince,
  getHistoryProvince: getHistoryProvince,
  getHotProvince: getHotProvince,
  getDefaultStore: getDefaultStore,
  getStoreLines: getStoreLines
}